on: 
   push:
       branches:
          - main
          - "release/**"
   pull_request:
        branches:
           - main
           - "release/**"

jobs: 
   test:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v5.0.0

        - name: code test
          run: npm test

       
    
  